services:
  api:
    build:
      context: .
      dockerfile: src/bin/api/Dockerfile
    container_name: base-backend-nodejs-api
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads

  scheduler:
    build:
      context: .
      dockerfile: src/bin/schedular/Dockerfile
    container_name: base-backend-nodejs-scheduler
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
